dist: focal
sudo: required
language:
  - cpp
cache:
  - ccache
compiler:
  - gcc
addons:
  apt:
    #sources:
      #- ubuntu-toolchain-r-test
    packages:
      #- gcc-6
      #- g++-6
      - cmake
jobs:
  include:
    - stage build_0:
      script: bash buildDep -i ~/ext_lib -n 1 -o openmesh
    - #
      script: bash buildDep -i ~/ext_lib -n 1 -o openvolumemesh
    - #
      script: bash buildDep -i ~/ext_lib -n 1 -o gmsh
    - #
      script: bash buildDep -i ~/ext_lib -n 1 -o cgm
    - stag build_1:
      script: bash buildDep -i ~/ext_lib -n 1 -o moab
  #- pwd
  #- cat /proc/cpuinfo
  #- cd gmsh
  #- mkdir build
  #- cd build
  #- cmake -DCMAKE_INSTALL_PREFIX=~/ext_lib -DENABLE_BUILD_SHARED=ON -DENABLE_PRIVATE_API=ON ..
  #- make
  # Run your build commands next
  #- echo "Execute buildDep..."
  #- cd sandbox
  #- bash buildDep -i ~/ext_lib -n 2 -o all
  #- chmod u+x buildDep
  #- ./buildDep -i ~/ext_lib -n 1 -o all
