dist: focal
sudo: required
language:
  - cpp
cache:
  - ccache
compiler:
  - gcc
addons:
  apt:
    #sources:
      #- ubuntu-toolchain-r-test
    packages:
      #- gcc-6
      #- g++-6
      - cmake
      
before_install:
  - echo "Before install"
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
  
jobs:
  include:
    - stage: build_0
      script: 
        - bash buildDep -i ~/ext_lib -n 2 -o openmesh
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
    - stage: build_0
      script:
        - bash buildDep -i ~/ext_lib -n 2 -o openvolumemesh
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
    - stage: build_0
      script: 
        - bash buildDep -i ~/ext_lib -n 2 -o gmsh
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
    - stage: build_0
      script: 
        - bash buildDep -i ~/ext_lib -n 2 -o cgm
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
    - stage: build_1
      script:
        - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
        - bash buildDep -i ~/ext_lib -n 2 -o moab
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
    - stage: "lsTRAVIS_BUILD_NUMBER"
      script:
        - ls ~/$TRAVIS_BUILD_NUMBER
  #- pwd
  #- cat /proc/cpuinfo
  #- cd gmsh
  #- mkdir build
  #- cd build
  #- cmake -DCMAKE_INSTALL_PREFIX=~/ext_lib -DENABLE_BUILD_SHARED=ON -DENABLE_PRIVATE_API=ON ..
  #- make
  # Run your build commands next
  #- echo "Execute buildDep..."
  #- cd sandbox
  #- bash buildDep -i ~/ext_lib -n 2 -o all
  #- chmod u+x buildDep
  #- ./buildDep -i ~/ext_lib -n 1 -o all
